### ISSUE TITLE
bibitex编译参考文献报错

### ISSUE THREAD

**Issue by Poofee** [dustincys/PlutoThesisProposal#5]
Command Line:   bibtex.exe "main"
Startup Folder: E:\PlutoThesisProposal-master

This is BibTeX, Version 0.99d (MiKTeX 2.9.6210 64-bit)
The top-level auxiliary file: main.aux
The style file: GBT7714-2005NLang-HIT.bst
new.block is an unknown function---line 73 of file GBT7714-2005NLang-HIT.bst
remove.dots is an unknown function---line 461 of file GBT7714-2005NLang-HIT.bst
remove.dots is an unknown function---line 514 of file GBT7714-2005NLang-HIT.bst
remove.dots is an unknown function---line 571 of file GBT7714-2005NLang-HIT.bst
remove.dots is an unknown function---line 616 of file GBT7714-2005NLang-HIT.bst
format.pages is an unknown function---line 1163 of file GBT7714-2005NLang-HIT.bst
format.pages is an unknown function---line 1194 of file GBT7714-2005NLang-HIT.bst
format.pages is an unknown function---line 1203 of file GBT7714-2005NLang-HIT.bst
format.pages is an unknown function---line 1233 of file GBT7714-2005NLang-HIT.bst
format.pages is an unknown function---line 1242 of file GBT7714-2005NLang-HIT.bst
*publisher is an unknown function---line 1929 of file GBT7714-2005NLang-HIT.bst
*　* is an unknown function---line 1938 of file GBT7714-2005NLang-HIT.bst
ouput is an unknown function---line 2064 of file GBT7714-2005NLang-HIT.bst
ouput is an unknown function---line 2068 of file GBT7714-2005NLang-HIT.bst
ouput is an unknown function---line 2102 of file GBT7714-2005NLang-HIT.bst
ouput is an unknown function---line 2105 of file GBT7714-2005NLang-HIT.bst
format.conference.title is an unknown function---line 2622 of file GBT7714-2005NLang-HIT.bst
format.cconference.title is an unknown function---line 2657 of file GBT7714-2005NLang-HIT.bst
Database file #1: reference.bib
You can't pop an empty literal stack for entry BEZOS02
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry OOSTRUM01
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry SHELL02
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry TEXGURU99
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry WANG00
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry Zhang2002
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry zhangsanfeng
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry Lin1992
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry McDonnell1994
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
Warning--there's a number but no volume in Yao1993
You can't pop an empty literal stack for entry Yao1993
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry Yao1993
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry Chen1992
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry Niwa1990
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry Niwa1990
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry wu1997
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry wu1997
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
Warning--empty year in wwwlixing
You can't pop an empty literal stack for entry wwwlixing
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry wwwlixing
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry wwwlixing
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
Warning--empty year in asdfafsdg
You can't pop an empty literal stack for entry asdfafsdg
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry asdfafsdg
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry asdfafsdg
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
Warning--empty year in wwwlixing234
You can't pop an empty literal stack for entry wwwlixing234
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry wwwlixing234
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
You can't pop an empty literal stack for entry wwwlixing234
while executing---line 3560 of file GBT7714-2005NLang-HIT.bst
(There were 43 error messages)

**Comment by dustincys** [comment]
这个是历史遗留问题，  GBT7714-2005NLang-HIT.bst 一直有这个bug，但这个报错不会影响输出结果。就一直没有修改。
https://github.com/dustincys/PlutoThesis 中更新了bst文件，这个文件不会报错。

**Comment by Poofee** [comment]
OK thanks
